export './domus/domus_screen.dart';
export './numerator/numerator_screen.dart';
export './bands/bands_screen.dart';
export './charta/charta_screen.dart';
export './Pokemon/pokemons_screen.dart';
export './Pokemon/pokemon_screen.dart';
export './Satus/satus_screen.dart';
export './canticum/canticum_screen.dart';
export './lectio/lectio_screen.dart';